# Common configuration values
common:
  # Security contexts applied at the Pod level
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroupChangePolicy: OnRootMismatch
    fsGroup: 1000

  # Common container security settings
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  # Common service ports
  ports:
    api: 80
    frontend: 80
    guacamole: 80
    guacd: 4822
    mysql: 3306

  # Database configuration
  database:
    host: mysql-guacamole
    port: "3306"
    user: "" # Set the database user
    password: "" # Set the database password
    guacamoleDb: guacamole_db
    desktopDb: desktop_manager

  # Credentials and secrets
  credentials:
    secretKey: "" # Set a secure secret key for the application
    guacamoleAdmin:
      username: "" # Set the Guacamole admin username
      password: "" # Set the Guacamole admin password
    desktopAdmin:
      username: "" # Set the Desktop Manager admin username
      password: "" # Set the Desktop Manager admin password

  # Rancher configuration
  rancher:
    apiUrl: "" # Set your Rancher API URL
    clusterId: "" # Set your Rancher cluster ID
    repoName: "" # Set your repository name
    token: "" # Set your Rancher API token

# Component-specific configurations
replicaCount: 1

#####################################################
# Desktop Manager API values
#####################################################
desktopApi:
  replicaCount: 1
  image: "glennfischer032/desktop-manager-api:latest" # Update with specific version if needed
  containerPort: 5000
  healthcheck:
    enabled: true
    path: /api/health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

#####################################################
# Desktop Manager Frontend values
#####################################################
desktopFrontend:
  replicaCount: 1
  image: "glennfischer032/desktop-manager-frontend:latest" # Update with specific version if needed
  containerPort: 5000
  healthcheck:
    enabled: true
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

#####################################################
# MySQL values
#####################################################
mysql:
  image: "mysql:8.0"
  initdbImage: "glennfischer032/guacamole-init-db:latest"
  persistence:
    enabled: true
    storageClass: "nfs-csi"
    accessMode: ReadWriteOnce
    size: 1Gi
  args:
    - "--default-authentication-plugin=mysql_native_password"
    - "--bind-address=0.0.0.0"
  healthcheck:
    enabled: true
    command: ["mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

#####################################################
# guacd values
#####################################################
guacd:
  image: "guacamole/guacd"
  logLevel: "info"

#####################################################
# guacamole (web app) values
#####################################################
guacamole:
  image: "glennfischer032/guac-no-root:latest"
  containerPort: 8080
