# Common configuration values
common:
  # Security contexts applied at the Pod level
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroupChangePolicy: OnRootMismatch
    fsGroup: 1000

  # Common container security settings
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  # Common service ports
  ports:
    api: 80
    frontend: 80
    guacamole: 80
    guacd: 4822
    postgres: 5432
    redis: 6379

  # Database configuration
  database:
    host: postgres-guacamole
    port: "5432"
    user: "guacamole_user" # Database user
    password: "" # Database password
    database: desktop_manager # Main database name

  # Credentials and secrets
  credentials:
    desktopAdmin:
      oidcSub: "" # Desktop Manager admin OIDC subject
    guacamoleJsonSecretKey: "" # Guacamole JSON auth secret key
    encryptionKey: "" # Fernet key for encryption
    desktopApiSecretKey: "" # Secret key for desktop API
    desktopFrontendSecretKey: "" # Secret key for desktop frontend if using debug mode, need to match with desktopApiSecretKey for debug login

  # Rancher configuration
  rancher:
    apiUrl: "" # Set your Rancher API URL
    clusterId: "" # Set your Rancher cluster ID
    repoName: "" # Set your repository name
    token: "" # Set your Rancher API token
    namespace: "" # Set your namespace

  # OIDC Configuration
  oidc:
    clientId: "" # Set your OIDC client ID
    clientSecret: "" # Set your OIDC client secret
    providerUrl: "" # Set your OIDC provider URL
    redirectUri: "" # Set your OIDC redirect URI

  # Social Auth Configuration
  socialAuth:
    oidcProviderUrl: "" # Set your Social Auth OIDC provider URL
    loginRedirectUrl: "" # Set your Social Auth login redirect URL
    loginErrorUrl: "" # Set your Social Auth login error URL
    oidcCallbackUrl: "" # Set your Social Auth OIDC callback URL
    oidcRedirectUri: "" # Set your Social Auth OIDC frontend redirect URI

# Component-specific configurations
replicaCount: 1

#####################################################
# Desktop Manager API values
#####################################################
desktopApi:
  replicaCount: 1
  image: "gitlab.fi.muni.cz:5050/xfischer/sensitive-desktop/desktop-manager-api:latest"
  containerPort: 5000
  healthcheck:
    enabled: true
    path: /api/health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

#####################################################
# Desktop Manager Frontend values
#####################################################
desktopFrontend:
  replicaCount: 1
  image: "gitlab.fi.muni.cz:5050/xfischer/sensitive-desktop/desktop-manager-frontend:latest"
  containerPort: 5000
  hostname: "manage-desktops"
  healthcheck:
    enabled: true
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

#####################################################
# PostgreSQL values
#####################################################
postgres:
  image: "postgres:16-alpine"
  persistence:
    enabled: true
    storageClass: "nfs-csi"
    accessMode: ReadWriteOnce
    size: 1Gi
  healthcheck:
    enabled: true
    command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

#####################################################
# guacd values
#####################################################
guacd:
  image: "guacamole/guacd"
  logLevel: "info"

#####################################################
# guacamole (web app) values
#####################################################
guacamole:
  image: "gitlab.fi.muni.cz:5050/xfischer/sensitive-desktop/guac-no-root:latest"
  containerPort: 8080
  extensionPriority: "json"
  hostname: "guacamole"
#####################################################
# Redis values
#####################################################
redis:
  image: "redis:7-alpine"
  containerPort: 6379
  healthcheck:
    enabled: true
    command: ["redis-cli", "ping"]
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
