
# Block Desktop API ingress except for the Desktop Frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: desktop-api-policy-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "desktop-api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "desktop-frontend.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.desktopApi.containerPort }}
