apiVersion: v1
kind: Secret
metadata:
  name: desktop-api-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  rancher-token: {{ .Values.common.rancher.token | b64enc | quote }}
