apiVersion: v1
kind: ServiceAccount
metadata:
  name: desktop-api-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: desktop-api-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
rules:
  # Permissions for managing helm releases and related resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Permissions for helm chart management
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: desktop-api-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: desktop-api-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: desktop-api-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
