apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-api-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
spec:
  replicas: {{ .Values.desktopApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "desktop-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "desktop-api.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        command: ['sh', '-c', 'until mysqladmin ping -h mysql-{{ .Release.Name }} -u root -p{{ .Values.mysql.rootPassword }}; do echo waiting for mysql; sleep 2; done;']
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      containers:
      - name: desktop-api
        image: {{ .Values.desktopApi.image }}
        imagePullPolicy: IfNotPresent
        securityContext:
          {{- toYaml .Values.desktopApi.securityContext | nindent 12 }}
        env:
        {{- range $key, $value := .Values.desktopApi.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
          # Special handling for Rancher token from secret
          - name: RANCHER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: desktop-api-{{ $.Release.Name }}
                key: rancher-token
        ports:
        - containerPort: {{ .Values.desktopApi.containerPort }}
          name: http
        {{- if .Values.desktopApi.healthcheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.desktopApi.healthcheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.desktopApi.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.desktopApi.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.desktopApi.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.desktopApi.healthcheck.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.desktopApi.healthcheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.desktopApi.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.desktopApi.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.desktopApi.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.desktopApi.healthcheck.failureThreshold }}
        {{- end }}
