apiVersion: v1
kind: Secret
metadata:
  name: desktop-api-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  {{- if .Values.desktopApi.existingRancherToken }}
  # Use existing token if provided
  rancher-token: {{ .Values.desktopApi.existingRancherToken | b64enc }}
  {{- else if .Values.desktopApi.rancherToken }}
  # Fallback to direct token (not recommended for production)
  rancher-token: {{ .Values.desktopApi.rancherToken | b64enc }}
  {{- else }}
  {{- required "A valid Rancher API token is required. Set either desktopApi.rancherToken or desktopApi.existingRancherToken" nil -}}
  {{- end }}
