apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: guacamole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guacamole.selectorLabels" . | nindent 8 }}
        component: guacamole
    spec:
      securityContext:
        {{- toYaml .Values.common.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-guacd
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z -w2 guacd-{{ .Release.Name }} {{ .Values.common.ports.guacd }}; do echo waiting for guacd; sleep 2; done;']
        securityContext:
          {{- toYaml .Values.common.containerSecurityContext | nindent 10 }}
          runAsUser: 1000
      containers:
      - name: guacamole
        image: {{ .Values.guacamole.image }}
        imagePullPolicy: IfNotPresent
        securityContext:
          {{- toYaml .Values.common.containerSecurityContext | nindent 10 }}
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: GUACD_HOSTNAME
          value: {{ printf "guacd-%s" .Release.Name | quote }}
        - name: GUACD_PORT
          value: {{ .Values.common.ports.guacd | quote }}
        # JSON Authentication configuration
        - name: GUACAMOLE_EXTENSION_PRIORITY
          value: {{ .Values.guacamole.extensionPriority | quote }}
        - name: GUACAMOLE_JSON_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "guacamole.fullname" . }}-credentials
              key: guacamoleJsonSecretKey
        # Direct property mapping for Docker container
        - name: JSON_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "guacamole.fullname" . }}-credentials
              key: guacamoleJsonSecretKey
        - name: EXTENSION_PRIORITY
          value: {{ .Values.guacamole.extensionPriority | quote }}
        ports:
        - containerPort: {{ .Values.guacamole.containerPort }}
          name: http
        livenessProbe:
          httpGet:
            path: /guacamole/
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /guacamole/
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
