apiVersion: v1
kind: Service
metadata:
  name: guacd-{{ .Release.Name }}
  labels:
    app: guacamole
    component: guacd
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
  - name: guacd
    port: {{ .Values.guacd.servicePort }}
    targetPort: {{ .Values.guacd.servicePort }}
  selector:
    app: guacamole
    component: guacd
    release: "{{ .Release.Name }}"
