apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-credentials
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
type: Opaque
stringData:
  # Use values from values.yaml which will be pre-populated by our script
  secretKey: {{ .Values.common.credentials.secretKey }}
  encryptionKey: {{ .Values.common.credentials.encryptionKey }}
  guacamoleJsonSecretKey: {{ .Values.common.credentials.guacamoleJsonSecretKey }}
  dbPassword: {{ .Values.common.database.password }}
  oidcClientSecret: {{ .Values.common.oidc.clientSecret }}
  rancherToken: {{ .Values.common.rancher.token }}
