apiVersion: v1
kind: Service
metadata:
  name: desktop-api-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.desktopApi.servicePort }}
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    {{- include "desktop-api.selectorLabels" . | nindent 4 }} 