apiVersion: v1
kind: Service
metadata:
  name: guacamole-{{ .Release.Name }}
  labels:
    app: guacamole
    component: guacamole
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.guacamole.servicePort }}
    targetPort: {{ .Values.guacamole.containerPort }}
  selector:
    app: guacamole
    component: guacamole
    release: "{{ .Release.Name }}"
