apiVersion: v1
kind: Service
metadata:
  name: desktop-frontend-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: desktop-frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.common.ports.frontend }}
    targetPort: {{ .Values.desktopFrontend.containerPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "desktop-frontend.selectorLabels" . | nindent 4 }}
