repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
        exclude: ^(.*\/tests\/|tests\/|.*test_.*\.py)
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(\.\.\/guacamole-helm\/.*$|guacamole-helm\/.*$)
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: local
    hooks:
      - id: check-sass-compiled
        name: Check if SASS files have been compiled to CSS
        entry: python app/scripts/check_sass_compiled.py
        language: system
        pass_filenames: false
        files: ^app/scss/.*\.scss$

      - id: pytest-check
        name: pytest-check
        entry: python -m pytest app/tests/
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest-cov
        name: pytest-coverage
        entry: python -m pytest app/tests/ --cov=app --cov-report=term-missing:skip-covered
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]
