[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "desktop-frontend"
version = "0.1.0"
description = "Desktop Manager Frontend"
authors = [{name = "Glenn"}]
requires-python = ">=3.11"
dependencies = [
    "flask==3.0.0",
    "pyotp==2.8.0",
    "werkzeug==3.0.0",
    "qrcode==7.3.1",
    "pillow==10.0.1",
    "requests==2.31.0",
    "pyjwt==2.8.0",
    "gunicorn==23.0.0"
]

[tool.setuptools]
packages = {find = {where = ["."]}}
