# Block guacd ingress except for guacamole
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: guacd-policy-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
      component: guacd
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "guacamole.selectorLabels" . | nindent 10 }}
          component: guacamole
    ports:
    - protocol: TCP
      port: {{ .Values.common.ports.guacd }}
