apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-{{ .Release.Name }}
  labels:
    app: guacamole
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    component: mysql
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
