apiVersion: v1
kind: Service
metadata:
  name: mysql-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: mysql
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.common.ports.mysql }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "guacamole.selectorLabels" . | nindent 4 }}
    component: mysql
