apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    component: redis
spec:
  ports:
  - port: {{ .Values.common.ports.redis }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: redis-{{ .Release.Name }}
