apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: postgres-init-job
      labels:
        {{- include "guacamole.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.common.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-guacamole {{ .Values.common.ports.postgres }}; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: init-postgres
        securityContext:
          {{- toYaml .Values.common.containerSecurityContext | nindent 12 }}
        image: {{ .Values.postgres.initdbImage }}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          echo "Initializing PostgreSQL database..."

          # Wait for PostgreSQL to be ready
          until PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres-guacamole -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c '\q'; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done

          echo "PostgreSQL is up - executing initialization scripts"

          # Execute initialization scripts
          PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres-guacamole -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /sql/01-guacamole-init.sql
          PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres-guacamole -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /sql/02-guacamole-init-users.sql
          PGPASSWORD=${POSTGRES_PASSWORD} psql -h postgres-guacamole -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /sql/03-init.sql

          echo "Database initialization completed successfully"
        env:
        - name: POSTGRES_USER
          value: {{ .Values.common.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.common.database.password }}
        - name: POSTGRES_DB
          value: {{ .Values.common.database.database }}
        volumeMounts:
        - name: init-scripts
          mountPath: /sql
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
