# Block Postgres ingress except for the Desktop API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-policy-{{ .Release.Name }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: postgres-guacamole
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "desktop-api.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.common.ports.postgres }}
