repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --select=F401,F403,F405]
        exclude: ^(.*\/tests\/|tests\/|.*test_.*\.py)
      - id: ruff-format
        exclude: ^(.*\/tests\/|tests\/|.*test_.*\.py)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(\.\.\/guacamole-helm\/.*$|guacamole-helm\/.*$)
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
